[[redirects]]
from = "/admin/*"
to = "adminhome"
status = 200

[[redirects]]
from = "/student/*"
to = "studenthome"
status = 200

[[redirects]]
from = "/counsellor/*"
to = "counsellorhome"
status = 200
